# PodDisruptionBudget for analytics-platform-api
# With 3 replicas, keeping 2 available ensures true HA during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: analytics-platform-api-pdb
  namespace: analytics-platform
  labels:
    app: analytics-platform-api
    component: backend
spec:
  minAvailable: 2  # Ensures 2 pods always serving traffic (out of 3 replicas)
  selector:
    matchLabels:
      app: analytics-platform-api
  unhealthyPodEvictionPolicy: IfHealthyBudget  # Allows stuck pods to be evicted

---
# PodDisruptionBudget for analytics-platform-worker
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: analytics-platform-worker-pdb
  namespace: analytics-platform
  labels:
    app: analytics-platform-worker
    component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: analytics-platform-worker
  unhealthyPodEvictionPolicy: IfHealthyBudget