receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  # Prometheus metrics receiver
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Batch processor for better performance
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s

  # Resource processor to add/modify resource attributes
  resource:
    attributes:
      - key: service.name
        value: strellerminds-backend
        action: upsert
      - key: deployment.environment
        value: ${ENV:development}
        action: upsert

  # Filter processor to remove sensitive data
  filter:
    traces:
      span:
        - 'attributes["http.request.headers.authorization"]'
        - 'attributes["db.parameters"]'
        - 'attributes["payment.card.number"]'

  # Sampling processor
  probabilistic_sampler:
    sampling_percentage: 10.0

exporters:
  # Jaeger exporter
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Zipkin exporter
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: json

  # OTLP exporter for external systems
  otlp:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: strellerminds

  # Logging exporter for debugging
  logging:
    loglevel: info

  # File exporter for backup
  file:
    path: /tmp/traces.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, filter, probabilistic_sampler, batch]
      exporters: [jaeger, zipkin, otlp, logging, file]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [logging, file]

  extensions: [health_check, pprof, zpages]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
