title = "Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "Allowlist for false positives"

paths = [
  '''\.md$''',
  '''package-lock\.json$''',
  '''\.test\.(js|ts)x?$''',
  '''\.spec\.(js|ts)x?$''',
  '''\.snap$''',
]

regexes = [
  '''example\.com''',
  '''test@test\.com''',
  '''localhost''',
  '''127\.0\.0\.1''',
  '''dummy''',
  '''placeholder''',
  '''fake[_-]?secret''',
  '''mock[_-]?api[_-]?key''',
]

commits = []

stopwords = [
  "example",
  "test",
  "demo",
  "sample",
  "placeholder",
]