# name: E2E Tests

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   e2e:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:13
#         ports:
#           - 5432:5432
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: strellerminds_test
#         options: >-
#           --health-cmd "pg_isready -U postgres"
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run E2E tests
#         env:
#           DB_HOST: localhost
#           DB_PORT: 5432
#           DB_USER: postgres
#           DB_PASSWORD: postgres
#           DB_NAME: strellerminds_test
#           JWT_SECRET: test-secret
#           STELLAR_NETWORK: testnet
#         run: npm run test:e2e
