name: Lockfile Guard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_lockfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enforce package-lock.json only
        id: lockfile_check
        shell: bash
        run: |
          echo "Scanning repository for unwanted lockfiles..."

          # Use find with -prune to efficiently exclude common directories (node_modules, .git)
          # Search for common lockfile names and general patterns, excluding package-lock.json

          UNWANTED_LOCKFILES=$(find . -type d \( -name node_modules -o -name .git \) -prune -o -type f \( \
              -name "yarn.lock" -o \
              -name "pnpm-lock.yaml" -o \
              -name "pnpm-lock.json" -o \
              -name "npm-shrinkwrap.json" -o \
              -name "*lockfile" \
          \) -not -name "package-lock.json" -print)

          # Remove common false positives like .github/dependabot.lock or empty lines
          # Note: The -prune helps, but this grep ensures absolute cleanliness
          CLEANED_LOCKFILES=$(echo "$UNWANTED_LOCKFILES" | grep -v "dependabot.lock" | grep -v "^$")

          if [ -n "$CLEANED_LOCKFILES" ]; then
              echo "--------------------------------------------------------"
              # Use GitHub annotation for maximum visibility
              echo "::error::🚨 FAILURE: UNWANTED LOCKFILES DETECTED 🚨"
              echo "Only 'package-lock.json' is permitted in this repository."
              echo "Please remove the following files and commit the change:"
              echo "$CLEANED_LOCKFILES"
              echo "--------------------------------------------------------"
              exit 1
          else
              echo "✅ Success: No forbidden lockfiles were detected."
          fi
