name: SDK Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build-generate-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build backend
        run: npm run build

      - name: Generate OpenAPI spec
        run: npm run generate:openapi
        env:
          NODE_ENV: openapi

      - name: Verify OpenAPI output exists
        run: |
          test -f openapi.json || (echo 'openapi.json not found after generation' && exit 1)
          echo "OpenAPI spec size:" && wc -c openapi.json

      - name: Determine package version
        id: pkg
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Verify tag and package.json version alignment
        run: |
          TAG=${GITHUB_REF_NAME#v}
          PKG=${{ steps.pkg.outputs.version }}
          echo "Tag version: $TAG"
          echo "Package version: $PKG"
          if [ "$TAG" != "$PKG" ]; then
            echo "Tag ($TAG) does not match package.json version ($PKG)." >&2
            exit 1
          fi

      - name: Generate TypeScript Axios SDK
        run: |
          npx -y @openapitools/openapi-generator-cli generate \
            -i ./openapi.json \
            -g typescript-axios \
            -o ./sdk/typescript \
            --additional-properties npmName=@starkmindshq/strellerminds-sdk,npmVersion=${{ steps.pkg.outputs.version }},supportsES6=true,typescriptThreePlus=true,withSeparateModelsAndApi=true

      - name: Archive SDK output
        run: |
          cd sdk
          zip -r typescript-sdk-${{ steps.pkg.outputs.version }}.zip typescript

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: SDK Release ${{ steps.pkg.outputs.version }}
          body: |
            Automated SDK generation for tag ${{ github.ref_name }}.

            OpenAPI specification (downloadable): https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/openapi.json

            Generated TypeScript Axios SDK is attached as a zip asset.

            npm package (if available): @starkmindshq/strellerminds-sdk@${{ steps.pkg.outputs.version }}
          files: |
            openapi.json
            sdk/typescript-sdk-${{ steps.pkg.outputs.version }}.zip

      - name: Publish SDK to npm (optional)
        if: ${{ secrets.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd sdk/typescript
          npm publish --access public